/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form.input;

import br.entidade.Convenio;
import br.entidade.MascaraConvenio;
import br.entidade.business.Business;
import form.JFPrincipal;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.RollbackException;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import br.data.bancodedados.CriaConexao;
import superior.mensagens.ErroMensagens;

/**
 *
 * @author Adriano
 */
public class JIDePara extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIDePara
     */
    public JIDePara() {
        initComponents();
        iniciarComponentes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jPanel1 = new javax.swing.JPanel();
        masterScrollPane = new javax.swing.JScrollPane();
        masterTable = new javax.swing.JTable();
        convIdLabel = new javax.swing.JLabel();
        convCodCodLabel = new javax.swing.JLabel();
        convNmNomeLabel = new javax.swing.JLabel();
        fkConvLabel = new javax.swing.JLabel();
        convIdField = new javax.swing.JTextField();
        convCodCodField = new javax.swing.JTextField();
        convNmNomeField = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        refreshButton = new javax.swing.JButton();
        newButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        fkConvCombo = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        shareFild = new javax.swing.JTextField();
        shareButton = new javax.swing.JButton();
        jLabel = new javax.swing.JLabel();

        setTitle("DePara");

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        masterTable.setModel(dtm);
        masterTable.setSelectionMode(ListSelectionM­odel.MULTIPLE_INTERVAL_SELECTION);
        lsm = masterTable.getSelectionModel();
        lsm.addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    jTTabelaLinhaSelecionada(masterTable);
                }
            }
        });
        masterScrollPane.setViewportView(masterTable);
        masterTable.getColumnModel().getColumn(0).setPreferredWidth(40);

        convIdLabel.setText("ID:");

        convCodCodLabel.setText("Cod:");

        convNmNomeLabel.setText("Nome:");

        fkConvLabel.setText("Mascara:");

        convIdField.setEditable(false);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), convIdField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), convCodCodField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        convCodCodField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                convCodCodFieldKeyReleased(evt);
            }
        });

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), convNmNomeField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        convNmNomeField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                convNmNomeFieldKeyReleased(evt);
            }
        });

        saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/save.png"))); // NOI18N
        saveButton.setToolTipText("Salvar");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        refreshButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/refresh.png"))); // NOI18N
        refreshButton.setToolTipText("Atualizar");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        newButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/new.png"))); // NOI18N
        newButton.setToolTipText("Novo");
        newButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newButtonActionPerformed(evt);
            }
        });

        deleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/Delete.png"))); // NOI18N
        deleteButton.setToolTipText("Deletar");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), deleteButton, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        fkConvCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), fkConvCombo, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        fkConvCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fkConvComboActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/exit.png"))); // NOI18N
        jButton1.setToolTipText("Sair");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(newButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(refreshButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saveButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fkConvLabel)
                            .addComponent(convNmNomeLabel)
                            .addComponent(convCodCodLabel)
                            .addComponent(convIdLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(convIdField, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                            .addComponent(convCodCodField, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                            .addComponent(convNmNomeField, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                            .addComponent(fkConvCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(masterScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(masterScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(convIdLabel)
                    .addComponent(convIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(convCodCodLabel)
                    .addComponent(convCodCodField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(convNmNomeLabel)
                    .addComponent(convNmNomeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fkConvCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fkConvLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton)
                    .addComponent(refreshButton)
                    .addComponent(deleteButton)
                    .addComponent(newButton)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        shareFild.setNextFocusableComponent(shareButton);
        shareFild.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                shareFildKeyReleased(evt);
            }
        });

        shareButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/search.png"))); // NOI18N
        shareButton.setToolTipText("Pesquisar");
        shareButton.setNextFocusableComponent(masterScrollPane);
        shareButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shareButtonActionPerformed(evt);
            }
        });

        jLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel.setText("Nome/Cod:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(shareFild)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(shareButton)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(shareButton)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(shareFild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        
        try {
            dao.salvar();
        } catch (RollbackException e) {
            dao.getEntityManager().getTransaction().begin();
            dao.refresh();
            list = dao.findAll(Convenio.class);
            ErroMensagens.getInstancia().ErroMensagem("Você deve estar cometendo um dos seguntes erros. \n"
                                                    + "1 - Cod vazio. \n"
                                                    + "2 - Descricao vazia. \n"
                                                    + "3 - Cod já cadastrado. ");
            System.err.println(e);
        }
        mostraPesquisa();
    }//GEN-LAST:event_saveButtonActionPerformed

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        
        dao.refresh();
        list = dao.findAll(Convenio.class);
        mostraPesquisa();
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void newButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newButtonActionPerformed
        Convenio s = new Convenio();
        dao.criar(s);
        list.add(s);
        mostraPesquisa();
        int row = list.size() - 1;
        masterTable.setRowSelectionInterval(row, row);
        masterTable.scrollRectToVisible(masterTable.getCellRect(row, 0, true));
    }//GEN-LAST:event_newButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        int[] selected = masterTable.getSelectedRows();
        List<Convenio> toRemove = new ArrayList<>(selected.length);
        for (int idx = 0; idx < selected.length; idx++) {
                Convenio s = list.get(masterTable.convertRowIndexToModel(selected[idx]));
                toRemove.add(s);
                dao.remover(s);
        }
        list.removeAll(toRemove);
        mostraPesquisa();
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void convCodCodFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_convCodCodFieldKeyReleased
        // TODO add your handling code here:
        try {
            list.get(masterTable.getSelectedRow()).setCodigo(Integer.valueOf(convCodCodField.getText()));
            masterTable.setValueAt(convCodCodField.getText(), masterTable.getSelectedRow(), 2);
        } catch (NumberFormatException e) {
            ErroMensagens.getInstancia().PerigoMensagem("Este campo recebe apenas numeros!");
            convCodCodField.setText(String.valueOf(list.get(masterTable.getSelectedRow()).getCodigo()));
            masterTable.setValueAt(convCodCodField.getText(), masterTable.getSelectedRow(), 2);
        }
    }//GEN-LAST:event_convCodCodFieldKeyReleased

    private void convNmNomeFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_convNmNomeFieldKeyReleased
        // TODO add your handling code here:
        convNmNomeField.setText(convNmNomeField.getText().toUpperCase());
        list.get(masterTable.getSelectedRow()).setDescricao(convNmNomeField.getText());
        masterTable.setValueAt(convNmNomeField.getText(), masterTable.getSelectedRow(), 1);
    }//GEN-LAST:event_convNmNomeFieldKeyReleased

    private void fkConvComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fkConvComboActionPerformed
        // TODO add your handling code here:
        if (masterTable.getSelectedRow() != -1) {
            if (fkConvCombo.getSelectedItem() != null) {
                list.get(masterTable.getSelectedRow()).setMascaraConvenioId(box.get(fkConvCombo.getSelectedIndex() - 1));
            }
            masterTable.setValueAt(fkConvCombo.getSelectedItem(), masterTable.getSelectedRow(), 3);
        }
    }//GEN-LAST:event_fkConvComboActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dao.getEntityManager().close();
        JFPrincipal.setD(null);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void shareButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shareButtonActionPerformed
        // TODO add your handling code here:
        try{
            list = dao.getEntityManager().createNamedQuery("Convenio.findByCodigo",Convenio.class)
                    .setParameter("codigo", Integer.parseInt(shareFild.getText())).getResultList();
        }catch(NumberFormatException n){
            list = dao.getEntityManager().createNamedQuery("Convenio.findByDescricao", Convenio.class)
                    .setParameter("descricao", "%" + shareFild.getText() + "%").getResultList();
        }
        mostraPesquisa();
    }//GEN-LAST:event_shareButtonActionPerformed

    private void shareFildKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_shareFildKeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            shareButton.requestFocus();
        }
    }//GEN-LAST:event_shareFildKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField convCodCodField;
    private javax.swing.JLabel convCodCodLabel;
    private javax.swing.JTextField convIdField;
    private javax.swing.JLabel convIdLabel;
    private javax.swing.JTextField convNmNomeField;
    private javax.swing.JLabel convNmNomeLabel;
    private javax.swing.JButton deleteButton;
    private javax.swing.JComboBox fkConvCombo;
    private javax.swing.JLabel fkConvLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane masterScrollPane;
    private javax.swing.JTable masterTable;
    private javax.swing.JButton newButton;
    private javax.swing.JButton refreshButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton shareButton;
    private javax.swing.JTextField shareFild;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
    private List<Convenio> list;
    private DefaultTableModel dtm = new DefaultTableModel(null, new String[]{"Id", "Nome", "Codigo", "Mascara"});
    private ListSelectionModel lsm;
    private List<MascaraConvenio> box;
    private Business dao;

    private void iniciarComponentes() {
        EntityManager emf = CriaConexao.getInstance().getEntityManager();
        dao = new Business();
        dao.getEntityManager().getTransaction().begin();
        listarPesquisa();
        listarBox();
    }

    private void listarPesquisa() {
        list = dao.findAll(Convenio.class);
        mostraPesquisa();
    }

    private void mostraPesquisa() {
        removeDesativado();
        while (dtm.getRowCount() > 0) {
            dtm.removeRow(0);
        }
        if (list.isEmpty()) {
            ErroMensagens.getInstancia().InformacaoMensagem("Nenhum resultado encontrado");
        } else {

            String[] linha = new String[]{null, null, null, null};
            int i = 0;
            for (Convenio sftConvenios : list) {
                dtm.addRow(linha);
                dtm.setValueAt(sftConvenios.getId(), i, 0);
                dtm.setValueAt(sftConvenios.getDescricao(), i, 1);
                dtm.setValueAt(sftConvenios.getCodigo(), i, 2);
                dtm.setValueAt(null, i, 3);
                if (sftConvenios.getMascaraConvenioId() != null) dtm.setValueAt(sftConvenios.getMascaraConvenioId().getDescricao(), i, 3);
                i++;
            }
        }
    }

    public void jTTabelaLinhaSelecionada(JTable masterTable) {
        try{
            convIdField.setText(String.valueOf(list.get(masterTable.getSelectedRow()).getId()));
            convNmNomeField.setText(list.get(masterTable.getSelectedRow()).getDescricao());
            convCodCodField.setText(String.valueOf(list.get(masterTable.getSelectedRow()).getCodigo()));
            fkConvCombo.setSelectedItem(null);
            if (list.get(masterTable.getSelectedRow()).getMascaraConvenioId() != null)
                fkConvCombo.setSelectedItem(list.get(masterTable.getSelectedRow()).getMascaraConvenioId().getDescricao());
            
        } catch(ArrayIndexOutOfBoundsException e){
            convIdField.setText("");
            convNmNomeField.setText("");
            convCodCodField.setText("");
            fkConvCombo.setSelectedItem(null);
        }
    }

    private void listarBox() {
        box = dao.findAll(MascaraConvenio.class);
        fkConvCombo.removeAllItems();
        fkConvCombo.addItem(null);
        for (MascaraConvenio sftConv : box) {
//            if(!sftConv.getConvNmNmconv().contains("ZZ "))
            fkConvCombo.addItem(sftConv.getDescricao());
        }
    }
//    private void desativarObjeto(Convenioenios s) {
//        s.setConvNmNome("ZZ " + s.getConvNmNome());
//        dao.edit(s);
//    }
    private void removeDesativado() {
        List<Convenio> toRemove = new ArrayList<>();
        for (Convenio sftConvenios : list) {
            try{ if (sftConvenios.getDescricao().contains("ZZ ")) toRemove.add(sftConvenios);}catch(NullPointerException e){}
        }
        list.removeAll(toRemove);
    }

}
